<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nadiia Savenko</title>
</head>
<body>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus nobis esse dicta tenetur! Odio exercitationem, nihil a eveniet, saepe animi dicta explicabo, eum assumenda labore autem. Porro, culpa ut! Est. </p>
     <a href="https://liceum.teb.pl">Wejdź na stronę LO TEB Edukacja</a>

     <h1>Przkład h1</h1>
     <h2>Przykład h2</h2>
     <h3>Przykład h3</h3>
     <h4>Przykład h4</h4>
     <h5>Przykład h5</h5>
     <h6>Przykład h6</h6>

     <hr>

     <!-- Zadnanie: zrób menu restauracji -->
     <!-- 2 kategorie dań, w każdej 2 dania -->
     <!-- znaczniki do użycia: h1, h2, h3, p -->
     
</body>
</html>